models/board.py
# *Created by zxiaobai on 17/1/11.
from . import ModelMixin
from . import db
from . import *


class Board(db.Model, ModelMixin):
    __tablename__ = 'boards'
    id = db.Column(db.Integer, primary_key=True)
    content = db.Column(db.String(225))
    created_time = db.Column(db.Integer)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))

    def __init__(self, form):
        self.content = form.get("content", '')
        self.created_time = date_time()

    def valid(self):
        return 101 > len(self.content) > 1

    def board_add(self, user):
        if self.valid():
            self.user_id = user.id
            self.save()
            return True, {'content': self.content,
                          'username': self.user.username,
                          'created_time': self.created_time,
                          'avatar': self.user.avatar,
                          'id': self.id,
                          }, '留言成功'

        return False, None, '留言不得少于2个字符多于100个字符'

models/weibo.py
# *Created by zxiaobai on 17/1/22.
from . import ModelMixin
from . import db
from . import date_time


class Weibo(db.Model, ModelMixin):
    __tablename__ = 'weibos'
    id = db.Column(db.Integer, primary_key=True)
    weibo = db.Column(db.String(225))
    created_time = db.Column(db.Integer)
    comments_num = db.Column(db.Integer, default=0)
    like_nums = db.Column(db.Integer, default=0)

    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))

    weibo_comments = db.relationship('WeiboComment', backref='weibo', lazy='dynamic',
                                     order_by="desc(WeiboComment.id)")

    def __init__(self, form):
        self.weibo = form.get('weibo', '')
        self.created_time = date_time()

    def like(self, user):
        u_likes = user.like_weibo.split(';')
        if str(self.id) in u_likes:
            self.like_nums -= 1
            u_likes.remove(str(self.id))
            user.like_weibo = ';'.join(u_likes)
            user.save()
            return True, {'like_nums': self.like_nums}, '取消点赞'
        user.like_weibo += (str(self.id) + ';')
        self.like_nums += 1
        self.save()
        return True, {'like_nums': self.like_nums}, '点赞成功'

    def valid(self):
        w = self.weibo.strip()
        l = len(w)
        if l < 3:
            return False, '微博太短了，不能少于 3 个字符'
        elif l > 100:
            return False, '微博太长了，不能超过 100 个字符'
        return True, '发送成功'

    def save_weibo(self, user):
        status, msg = self.valid()
        if status:
            self.user = user
            self.save()
            data = self.response()
        else:
            data = None
        return status, data, msg

    def delete_weibo(self):
        for i in self.comments:
            i.delete()
        self.delete()
        data = self.response()
        status = True
        msg = '微博删除成功'
        return status, data, msg

    def response(self):
        return dict(
            id=self.id,
            weibo=self.weibo,
            username=self.user.username,
            created_time=self.created_time,
            avatar=self.user.avatar,
            comments_num=self.comments_num,
            user_id=self.user.id)


class WeiboComment(db.Model, ModelMixin):
    __tablename__ = 'weibo_comments'
    id = db.Column(db.Integer, primary_key=True)
    comment = db.Column(db.String(225))
    created_time = db.Column(db.Integer)

    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    weibo_id = db.Column(db.Integer, db.ForeignKey('weibos.id'))

    def __init__(self, form):
        self.comment = form.get('comment', '')
        self.weibo_id = form.get('weibo_id', '')
        self.created_time = date_time()

    def valid(self):
        c = self.comment.strip()
        l = len(c)
        if l < 1:
            return False, '评论太短了，不能少于 1 个字符'
        elif l > 50:
            return False, '评论太长了，不能超过 50 个字符'
        return True, '发表评论成功'

    def save_comment(self, user, weibo):
        status, msg = self.valid()
        if status:
            self.user = user
            self.weibo = weibo
            self.weibo.comments_num += 1
            self.save()
            data = self.response()
        else:
            data = None
        return status, data, msg

    def response(self):
        return dict(comment=self.comment,
                    username=self.user.username,
                    created_time=self.created_time,
                    avatar=self.user.avatar,
                    user_id=self.user.id)

routes/board.py
# *Created by zxiaobai on 17/1/11.
from routes import *

from models.user import User
from models.board import Board

main = Blueprint('board', __name__)


@main.route('')
@current_user_required
def board(user):
    b = Board.query.all()
    return render_template('board.html', user=user, board=b)


@main.route('/add', methods=['POST'])
@current_user_required
def new_msg(user):
    form = request.form
    status, data, message = Board(form).board_add(user)
    return api_response(status, data, message)

routes/chat.py
# *Created by zxiaobai on 17/1/12.
import flask
import redis
import time
import json
from models.user import User

from routes import *

main = Blueprint('chat', __name__)


red = redis.Redis(host='localhost')
print('redis', red)
chat_channel = 'chat'


def stream():
    '''
    监听 redis 广播并 sse 到客户端
    '''
    # 对每一个用户 创建一个[发布订阅]对象
    pubsub = red.pubsub()
    # 订阅广播频道
    pubsub.subscribe(chat_channel)
    # 监听订阅的广播
    for message in pubsub.listen():
        print(message)
        if message['type'] == 'message':
            data = message['data'].decode('utf-8')
            # 用 sse 返回给前端
            yield 'data: {}\n\n'.format(data)


def current_time():
    return int(time.time())


@main.route('')
@current_user_required
def index_view(user):
    return flask.render_template('chat.html', user=user)


@main.route('/subscribe')
def subscribe():
    return flask.Response(stream(), mimetype="text/event-stream")


@main.route('/add', methods=['POST'])
@current_user_required
def chat_add(user):
    msg = request.get_json()
    name = user.username
    avatar = user.avatar
    content = msg.get('content', '')
    channel = msg.get('channel', '')
    r = {
        'name': name,
        'content': content,
        'channel': channel,
        'created_time': current_time(),
        'avatar': avatar,
    }
    message = json.dumps(r, ensure_ascii=False)
    print('debug', message)
    # 用 redis 发布消息
    red.publish(chat_channel, message)
    return 'OK'

routes/profile.py
# *Created by zxiaobai on 17/1/11.
from routes import *
from werkzeug.utils import secure_filename
from models.user import User

main = Blueprint('profile', __name__)

UPLOAD_FOLDER = 'static/avatar'
ALLOWED_EXTENSIONS = ['png', 'jpg', 'jpeg', 'gif']


def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1] in ALLOWED_EXTENSIONS


@main.route('/update', methods=['POST'])
@current_user_required
def update(user):
    form = request.form
    user.update(form)
    msg = '修改成功'
    return api_response(True, message=msg)


@main.route('/upload', methods=['GET', 'POST'])
@current_user_required
def upload(user):
    if request.method == 'GET':
        return redirect(url_for('node.index'))

    elif request.method == 'POST':
        file = request.files['file']
        if file and allowed_file(file.filename):
            fname = user.username +secure_filename(file.filename)
            file.save(os.path.join(UPLOAD_FOLDER, fname))
            user.avatar = fname
            user.save()
            return redirect(url_for('user.profile', username=user.username))
        return redirect(url_for('user.profile', username=user.username))

routes/weibo.py
# *Created by zxiaobai on 17/1/22.
from routes import *

from models.user import User
from models.weibo import Weibo, WeiboComment

main = Blueprint('weibo', __name__)


@main.route('')
@current_user_required
def index(user):
    items_per_page = 20
    page = request.args.get('page', 1, type=int)
    # desc按倒序  asc按正序
    w = Weibo.query.order_by(Weibo.id.desc()).paginate(page, items_per_page, False)
    return render_template('weibo.html', user=user, weibo=w)


@main.route('/add', methods=['POST'])
@current_user_required
def new_weibo(user):
    form = request.form
    status, data, message = Weibo(form).save_weibo(user)
    return api_response(status, data, message)


@main.route('/comment/add', methods=['POST'])
@current_user_required
def new_comment(user):
    form = request.form
    weibo = Weibo.query.get_or_404(form.get('weibo_id'))
    status, data, message = WeiboComment(form).save_comment(user, weibo)
    return api_response(status, data, message)


@main.route('/like/<int:id>')
@current_user_required
def like(user, id):
    w = Weibo.query.get_or_404(id)
    status, data, message = w.like(user)
    return api_response(status, data, message)

templates/alluser.html
{% extends 'base.html' %}

{% block title %}所有用户{% endblock %}

{% block head %}
<style>
.container{
    width: 50%;
}
.user-profile{
    background:white;
    padding: 20px;
    margin-bottom:20px;
}
</style>
{% endblock head %}

{% block body %}

<div class="alluser">
<ul class="user-list">
    {% for au in all_user %}
    <li class="user-profile z-depth-3">
        username: <a href="/profile/{{ au.username }}" style="color:mediumvioletred"><b>{{ au.username }}</b></a>
        <span class="right">id: {{ au.id }}</span>
        <p>e-mail: {{ au.email }}</p>
        <p>created-time: {{ au.created_time }}</p>
        <span class="right">admin: {{ au.admin }}</span>
        <p>unsafe: {{ au.unsafe }}</p>
    </li>
    {% endfor %}
</ul>
</div>

{% endblock body %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="shortcut icon" href="http://okwc2urj8.bkt.clouddn.com/static/img/favicon.ico">
    <link rel="Bookmark" href="http://okwc2urj8.bkt.clouddn.com/static/img/favicon.ico">
    <script src="http://okwc2urj8.bkt.clouddn.com/static/js/jquery.min.js"></script>
    <script src="http://okwc2urj8.bkt.clouddn.com/static/js/materialize.min.js"></script>
    <script src="http://okwc2urj8.bkt.clouddn.com/static/js/alertify.min.js"></script>
    <script src="http://okwc2urj8.bkt.clouddn.com/static/js/api.js"></script>
    <link rel="stylesheet" href="http://okwc2urj8.bkt.clouddn.com/static/css/materialize.min.css">
    <link rel="stylesheet" href="http://okwc2urj8.bkt.clouddn.com/static/css/animate.min.css">
    <link rel="stylesheet" href="http://okwc2urj8.bkt.clouddn.com/static/css/alertify.min.css">
    <style>
    body,html{
        height: 100%;
        background: #f5f8fa;
    }
    .container{
        margin-top: 20px;
        margin-bottom: 20px;
        width: 80%;
    }
    .footer-powered-all a, .footer-github a{
        color:#666;
    }
    .footer-powered-all a:hover, .footer-github a:hover{
        color:#eb7350;
    }
    </style>
    <title>{% block title %}Tree New Bee{% endblock title %}</title>
    <script>
        var bindClick =function () {
         $('nav').on('click', 'a', function(){
         if ($(this).hasClass('dropdown-button')){
             $(this).parent().removeClass('active');
             return false
         }
         $('li').removeClass('active');
         $(this).parent().addClass('active')
        });
        };
        $(document).ready(function () {
/*        var navColors = new Array('pink','purple','deep-purple','indigo',
        'blue','cyan','teal','grey','blue-grey','red')

        var navColor = navColors[Math.floor(Math.random()*navColors.length)];
        $('.nav-wrapper').addClass(navColor)
        $('.btn').addClass(navColor)
*/
        $(".dropdown-button").dropdown({ hover: true });
        bindClick();
        var pathname = location.pathname;       //找到这个页面的路径
        $('.navbar-fixed').find('a').each(function(){                 //遍历所有a标签
            var href = $(this).attr('href');        //获取连接地址
            if(href.indexOf(pathname) !=-1){        //看看是不是包含当前页的路径
                $(this).parent().addClass('active');//再给这个加上active
                }
            });
        });
    </script>
    {% block head %}
    {% endblock head %}
</head>
<body>
<div class="navbar-fixed">
    <nav class="z-depth-3 teal" style="min-width: 700px;">
    <ul id="dropdown1" class="dropdown-content">
        <li><a href="/profile/{{ user.username }}">个人中心</a></li>
        {% if user.admin == 'true' %}
        <li><a href="/qeertyuiopasdf">全部用户</a></li>
        {% endif %}
        <li><a href="/logout">登出</a></li>
    </ul>
    <div class="nav-wrapper">
    <a href="/" style="margin-left: 20px;"  class="brand-logo left">Tree New Bee</a>
    <ul class="right">
      <li><a href="/weibo">微博</a></li>
      <li><a href="/chat">聊天室</a></li>
      <li><a href="/board">留言&bug反馈</a></li>
      <!--
      <li><a href="#4">消息<span class="new badge blue-grey darken-3">3</span></a></li>
      -->
      <li><a class="dropdown-button" href='/profile/{{ user.username }}' data-activates="dropdown1">{{ user.username }}
           <img style="height:64px;width:64px;margin-left:10px;margin-right:-15px;" src='/static/avatar/{{ user.avatar }}' class="right avatar circle"></a></li>
    </ul>
    </div>
    </nav>
</div>

{% block header_img %}
{% endblock header_img %}

<div class="container">
    {% block body %}
    {% endblock body %}
</div>
<div class="footer" style="text-align: center;margin-top:80px;border-top: 2px solid #e1e8ed;">
 	<div class="footer-top">
		<div class="footer-top-all">
 			<div class="footer-github">
	 			<a href="https://github.com/zxiaobai225/TreeNewBee"><img src="http://okwc2urj8.bkt.clouddn.com/static/img/github.png" style="width: 30px;height: 30px;margin-bottom: -8px;"><b>Github</b></a>
			</div>
		</div>
	</div>
	  <div class="footer-powered">
	  	<div class="footer-powered-all">
		 	<a href="#"><b>Powered by Zxiaobai</b></a>
		 </div>
	  </div>
</div>
</body>
</html>

templates/board.html
{% extends 'base.html' %}
{% block head %}
    <script src="http://okwc2urj8.bkt.clouddn.com/static/js/board.js"></script>
    <style>
    .msgs{
        max-height: 500px;
        overflow-y: auto;
    }
    .board{
        background: white;
        padding: 40px 100px;
        border-radius: 5px;
    }
    </style>
{% endblock head %}
{% block title %}留言&bug反馈{% endblock title %}

{% block body %}
    <div class="board z-depth-3" style="min-width: 700px">
    <div class="msgs">
    {% for msg in board[::-1] %}
    <div style="margin-top: 5px;">
        <label style="margin-right: 50px">{{ msg.id }}楼</label>
        <label style="margin-right: 10px;">{{ msg.created_time }}</label>
        <a href="/profile/{{ msg.user.username }}"><img style="position:relative;top:14px;height:40px;width:40px" src="/static/avatar/{{ msg.user.avatar }}" class="circle z-depth-1"></a>
        <span style="margin-right: 10px;">
        <a style="color:mediumvioletred" href="/profile/{{ msg.user.username }}"><b>{{ msg.user.username }}</b></a>:</span>
        <span>{{ msg.content }}</span>
    </div>
    {% endfor %}
    </div>
    <div class="input-field">
    <textarea class="materialize-textarea content" name="content" length="100"></textarea>
    <button id="add" class="waves-effect waves-purple btn">留言</button>
    </div>
    </div>
{% endblock body %}

templates/chat.html
{% extends 'base.html' %}
{% block title %}聊天室{% endblock %}

{% block head %}
    <link rel="stylesheet" href="http://okwc2urj8.bkt.clouddn.com/static/css/chat.css">
    <script src="http://okwc2urj8.bkt.clouddn.com/static/js/chat.js"></script>
{% endblock head%}

{% block body %}
<div class="chat">
<div id='id-div-channels' class="rc-left">
    <h5>聊天室</h5>
    <a class="rc-channel" href="#">大厅</a>
    <a class="rc-channel" href="#">游戏</a>
    <a class="rc-channel" href="#">灌水</a>
</div>
<div class="rc-main">
<div id="id-div-chats">
</div>
    <div class="rc-input">
    <div class="input-field">
        <input type="text" id='id-input-content' maxlength="30" length="30">
        <button id='id-button-send' class="waves-effect waves-purple btn" type="button">发送消息</button>
    </div>
    </div>
</div>
</div>
{% endblock body %}

templates/index.html
{% extends "base.html" %}

{% block head %}
    <style>
    .header-img{
        background-image: url("http://okwc2urj8.bkt.clouddn.com/static/img/header.png");
        height: 100px;
    }
    .container{
        width: 500px;
    }
    .content{
        background:white;
        margin-bottom:20px;
        border-radius: 5px;
    }
    .in-content{
        padding:20px 0 20px 20px;
    }
    .wifi-img{
        text-align: center;
    }
    .like_dislike span{
        color: #888;
        margin-right:15px;
    }
    #gif-btn{
        width:480px;
    }
    </style>
    <script src="/static/js/qiqu.js"></script>
{% endblock head %}

{% block title %}Tree New Bee{% endblock title %}

{% block header_img %}
<div class="header-img">
</div>
{% endblock header_img %}

{% block body %}

<div class="all-content" data-page="{{ page }}">
<ul class="cell">
    {% for d in data %}
    <li class="content z-depth-3">
        <div class="in-content">
            <span><img class="circle" style="width: 50px;height: 50px" src="{{ d.avatar }}"></span>
            <b style="color:mediumvioletred;position: relative;top:-17px;">{{ d.username }}</b>
            <p>{{ d.title }}</p>
            <p>{{ d.content }}</p>
        </div>

        {% if d.data_gif == '' %}
        <div class="wifi-img">
            <img style="width: 480px;" src={{ d.wifi_img_url }}>
        </div>
        {% else %}
        <div class="wifi-img">
            <img class="gif-img" style="width: 480px;" src="{{ d.wifi_img_url }}" data-gif={{ d.data_gif }}>
            <button id="gif-btn" class="btn gif-btn">点击图片加载GIF</button>
        </div>
        {% endif %}

        {% if d.hot_comment != '' %}
        <div class="in-content">
            <p><span style="color: #de5025;">神评论：</span>{{ d.hot_comment }}</p>
        </div>
        {% endif %}
        <div class="like_dislike in-content">
            <span>顶:{{ d.like }}</span>
            <span>踩:{{ d.dislike }}</span>
        </div>
    </li>
    {% endfor %}
</ul>
</div>


<div class="loading" style="margin-top: 80px;display: none">
    <p style="text-align: center;font-size: 12px">正在疯狂加载...</p>
<div class="progress">
    <div class="indeterminate">
    </div>
</div>
</div>
{% endblock body %}

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <script src="http://okwc2urj8.bkt.clouddn.com/static/js/jquery.min.js"></script>
    <script src="http://okwc2urj8.bkt.clouddn.com/static/js/materialize.min.js"></script>
    <script src="http://okwc2urj8.bkt.clouddn.com/static/js/alertify.min.js"></script>
    <script src="/static/js/login.js"></script>
    <script src="http://okwc2urj8.bkt.clouddn.com/static/js/api.js"></script>
    <script src="/static/js/user.js"></script>
    <link rel="stylesheet" href="http://okwc2urj8.bkt.clouddn.com/static/css/materialize.min.css">
    <link rel="stylesheet" href="http://okwc2urj8.bkt.clouddn.com/static/css/animate.min.css">
    <link rel="stylesheet" href="http://okwc2urj8.bkt.clouddn.com/static/css/alertify.min.css">
    <link rel="stylesheet" href="http://okwc2urj8.bkt.clouddn.com/static/css/login.css">
    <title>登录注册</title>
    <script>
    var bindEventTestLogin = function () {
    $('.test-btn').click(function () {
        var parent = $(this).parents('.login')
        var data = {
            username: 123456,
            password: 123456,

        };
        var response = function (r) {
            if (r.success) {
                successView(parent.parents('.container'))
                location.href = "/"
            } else {
                alertify.error(r.message)
                $('.login').addClass('animated shake')
            }
        };
        api.userLogin(data, response)
    })
    };
    $(document).ready(function () {
        bindEventTestLogin();
    });
    </script>
</head>
<body>
<div class="container">
<div class="row login-row">
    <div class="login z-depth-4 col-center-block">
        <div class="input-field">
            <input type="text" class="username validate" maxlength="16" length="16" required >
            <label for="username">用户名</label>
        </div>
        <div class="input-field">
            <input type="password" class="password validate" maxlength="16" length="16" required>
            <label for="password">密码</label>
        </div>
        <br>
        <div class="btn-all">
            <a style="display: block; margin-bottom: 15px;" class="disabled login-btn waves-effect waves-purple btn">登录</a>
            <a style="display: block; margin-bottom: 15px;background: rgb(0, 152, 236)" class="test-btn waves-effect waves-purple btn">测试号一键登录</a>
            <a style="display: block;" href="#signup" class="waves-effect waves-purple btn go-register">前往注册</a>
        </div>
    </div>
</div>

<div class="row register-row animated flipInY hide">
    <div class="register z-depth-3 col-center-block">
        <div class="input-field">
            <input type="text" class="username1" maxlength="16" length="16" required>
            <label for="username">用户名</label>
            <p></p>
        </div>
        <div class="input-field">
            <input type="password" class="password1" maxlength="16" length="16" required>
            <label for="password">密码</label>
            <p></p>
        </div>
        <br>
        <div class="btn-all">
            <a style="display: block; margin-bottom: 15px;" class="disabled register-btn waves-effect waves-purple btn">注册</a>
            <a style="display: block;" href="#signin" class="waves-effect waves-purple btn go-login">前往登录</a>
        </div>
    </div>
</div>
</div>
</body>
</html>

templates/profile.html
{% extends "base.html" %}

{% block title %}个人中心{% endblock title %}

{% block head %}
    <script src="/static/js/profile.js"></script>
    <style>
    .profile{
        min-width: 800px;
        background: white;
        padding: 40px 100px;
        border-radius: 5px;
    }
    </style>
{% endblock head %}
{% block body %}
<div class="profile z-depth-3">
    {% if othuser.username == user.username %}
    <form style="margin-bottom: 10px" class="form-horizontal" action="{{ url_for('profile.upload') }}" method="post" enctype="multipart/form-data">
        <input class="form-control input" id="fileupload1" type="file" name="file">
        <input type="submit" value="上传" class="waves-effect waves-purple btn">
    </form><br>
    头像预览：
    <div>
        大：<img class="z-depth-1" style="width: 192px;height: 192px;" src="/static/avatar/{{ user.avatar }}">
        中：<img class="z-depth-1" style="width: 128px;height: 128px;" src="/static/avatar/{{ user.avatar }}">
        小：<img class="z-depth-1" style="width: 64px;height: 64px;" src="/static/avatar/{{ user.avatar }}">
    </div><br>
    <div class="input-field">
    <input type="text" length="16" class="password" name="password" value="{{ user.password }}">
    <label for="password">密码</label>
    </div><br>
    <div class="input-field">
    <input type="text" class="email" name="email" value="{{ user.email }}">
    <label for="email">E-mail</label>
    </div><br>
    <div class="input-field">
    <input type="text" class="qq" name="qq" value="{{ user.qq }}"><br>
    <label for="qq">QQ</label>
    </div><br>
    <div class="input-field">
    <textarea class="materialize-textarea signature" name="signature" length="100">{{ user.signature }}</textarea>
    <label for="signature">个性签名</label>
    </div>
    <button id="update" class="waves-effect waves-purple btn">保存</button>

    {% else %}
    <div>
    用户名: <span style="color:mediumvioletred;font-size: 20px">{{ othuser.username }}</span>
    <button style="margin-left: 165px" class="waves-effect waves-purple btn">关注</button>
    </div><br>
    头像预览：
    <div>
        大：<img class="z-depth-1" style="width: 192px;height: 192px;" src="/static/avatar/{{ othuser.avatar }}">
        中：<img class="z-depth-1" style="width: 128px;height: 128px;" src="/static/avatar/{{ othuser.avatar }}">
        小：<img class="z-depth-1" style="width: 64px;height: 64px;" src="/static/avatar/{{ othuser.avatar }}">
    </div><br>

    <div class="input-field">
    <input disabled type="text" name="email" value="{{ othuser.email }}">
    <label for="email">E-mail</label>
    </div><br>
    <div class="input-field">
    <input disabled type="text" class="qq" name="qq" value="{{ othuser.qq }}"><br>
    <label for="qq">QQ</label>
    </div><br>
    <div class="input-field">
    <textarea disabled class="materialize-textarea signature" name="signature" length="100">{{ othuser.signature }}</textarea>
    <label for="signature">个性签名</label>
    </div>
    {% endif %}
</div>
{% endblock body %}

templates/weibo.html
{% extends 'base.html' %}
{% block head %}
<link rel="stylesheet" href="http://okwc2urj8.bkt.clouddn.com/static/css/weibo.css">
<script src="http://okwc2urj8.bkt.clouddn.com/static/js/weibo.js"></script>
{% endblock head %}
{% block title %}微博{% endblock title %}

{% block body %}
<div class="weibo">
<div class="z-depth-3 add-weibo">
    <p>有什么新鲜事想告诉大家?</p>
    <textarea class="materialize-textarea content" name="content" length="100"></textarea>
    <button id="add" class="waves-effect waves-purple btn">发微博</button>
</div>

<div class="weibo-items">
    {% for w in weibo.items %}
    <div class="z-depth-3 weibo-item" data-id="{{ w.id }}">
        <div class="weibo-item-1">
            <div class="weibo-avartar">
                <a href="/profile/{{ w.user.username }}">
                    <img class="z-depth-2 circle avatar" src="/static/avatar/{{ w.user.avatar }}">
                </a>
            </div>
            <div class="weibo-item-2" style="margin-left: 60px;">
                <div class="weibo-username"><a href="/profile/{{ w.user.username }}"><b>{{ w.user.username }}</b></a></div>
                <div class="weibo-created-time"><p>{{ w.created_time }}</p></div>
                <div class="weibo-content"><p>{{ w.weibo }}</p></div>
            </div>
        </div>
        <div class="weibo-item-3">
            <a class="show-comment" href="javascript:">评论 <span>{{ w.comments_num }}</span></a>
            <a class="zan" href="javascript:">赞 <span>{{ w.like_nums }}</span></a>
        </div>
    <div class="comment-items" style="display:none;">
        <div class="weibo-comments-add">
            <textarea class="materialize-textarea comment" name="comment" length="50"></textarea>
            <button class="add-comment waves-effect waves-purple btn">发表评论</button>
        </div>
        <div class="weibo-comments">
            {% for c in w.weibo_comments %}
            <div class="comment-avatar">
                <a href="/profile/{{ c.user.username }}">
                    <img class="z-depth-2" src="/static/avatar/{{ c.user.avatar }}">
                </a>
            </div>
            <div class="weibo-comment">
                <div class="comment-username"><a href="/profile/{{ c.user.username }}">{{ c.user.username }}</a>: <span>{{ c.comment }}</span></div>
                <div class="comment-created-time"><p>{{ c.created_time }}</p></div>
            </div>
            {% endfor %}
        </div>
    </div>
    </div>
    {% endfor %}
</div>
    <div class="paginations" style="text-align: center">
    <ul class="pagination">
        {% if weibo.has_prev %}
            <li class="waves-effect"><a href="{{ url_for('weibo.index', page=weibo.prev_num) }}">＜</a></li>
        {% endif %}

        {% for i in range(1, weibo.pages + 1) %}
            {% if i == weibo.page %}
                <li class="active"><a>{{ i }}</a></li>
            {% else %}
                <li class="waves-effect"><a href="{{ url_for('weibo.index', page=i) }}">{{ i }}</a></li>
            {% endif %}
        {% endfor %}

        {% if weibo.has_next %}
            <li class="waves-effect"><a href="{{ url_for('weibo.index', page=weibo.next_num) }}">＞</a></li>
        {% endif %}
    </ul>
    </div>
</div>
{% endblock body %}